package com.example.LMrouting.model;

import lombok.*;
import java.time.LocalDate;

/**
 * SrRegionAssignment represents the assignment of a Service Representative (SR) to an affinity region.
 * 
 * This entity supports many-to-many relationships:
 * - Multiple SRs can be assigned to one region (for high-density areas)
 * - One SR can cover multiple adjacent regions (for low-density areas)
 * 
 * The isAutoSuggested flag indicates whether this assignment was generated by the 
 * auto-distribution algorithm or manually configured by a supervisor.
 * 
 * Pure POJO, no JPA annotations. All persistence is handled by InMemoryStore.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SrRegionAssignment {
    
    /**
     * Unique identifier for this assignment
     */
    private Long id;
    
    /**
     * Reference to the affinity region ID
     */
    private Long affinityRegionId;
    
    /**
     * Name of the Service Representative assigned to this region
     */
    private String srName;
    
    /**
     * Date when this assignment was created or last modified
     */
    private LocalDate assignmentDate;
    
    /**
     * Flag indicating whether this assignment was auto-suggested by the system
     * (true) or manually configured by a supervisor (false)
     */
    private boolean isAutoSuggested;
}
